project:
  type: website
  output-dir: docs

website:
  title: "spatial-causal.org"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - events.qmd
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



