project:
  type: website
  output-dir: docs

website:
  title: "spatial-causal.org"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - events.qmd
      - about.qmd
      - community.qmd
      - href: stcausal-2025/index.qmd
        text: STCausal2025

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



