---
title: "About"
---

This community has emerged from the initial [Dagstuhl seminar] (https://www.dagstuhl.de/24202) on Causal Inference for Spatial Data Analytics in 2024. It serves researchers and industry practitioners who share interest in causal inference and discovery (*aka* analysis) and are interested to explore how *space* (or geography) challenges assumptions and methodological approaches in causal analysis. We are interested in spatial confounding, the role of spatial autocorrelation between units (on treatments, effects, and covariates), and in practical aspects how to undertake spatial casual analysis.

To support systematic causal consideration in the diverse disciplines that deal with spatial concepts, incl. Earth science, epidemiology, transportation, urban planning, and economics, and statistics, by establishing a common conceptual, terminological, and methodological foundation that will bring these communities together in the first place by centering the spatial nature of data, and the understanding of their generation through geographical processes.

The terminology and methods that have emerged in causal inference is currently always, to an extent, alien to at least part of the community. We have the ambition to serve as a bridge between these disciplines, provide a platform for discussions, and share resources, tools and tutorials.